[package]
name = "circlet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8.16"
thiserror = "1.0"

[dev-dependencies]
num_cpus = "1.13.1"
core_affinity = "0.5.10"